### ISSUE TITLE
how to prove this line is O(k)

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode#118]
https://github.com/kamyu104/LeetCode/blob/9a2ac6f2893c462af73e2956444ebf1a47759d5a/C%2B%2B/super-ugly-number.cpp#L20

**Comment by kamyu104** [comment]
Each index would be increased at most n times, and there are k indexes. So the total complexity is O(n * k).
This line is O(k) on average, I'll update the code. Thank you!
