### ISSUE TITLE
comparison between method 1 and this hash method.

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode#119]
https://github.com/kamyu104/LeetCode/blob/77dda1c8348c2ad4e90da88919369281bb58de43/C%2B%2B/super-ugly-number.cpp#L103
When I go through this hash method, I have a question: when current` uglies[i] <-  uglies[j] * primes[k],` you check from `uglies[j + 1] `to find the first` x` that `uglies[x] * primes[k]` that is not in the heap. Is it possible that for all `x` in` [j + 1, i]`, `uglies[x] * primes[k]` is in the heap already? if so, then no new number will be added into the heap and we will lose the `primes[k]` in the future, which must be wrong. But, I guess when using hash set to check duplicates, every ugly number will be found the first time in ascending prime factors multiplication pattern like method 1. You explicitly use that ascending rule in method 1, but you do not in method 4. If using hash set can achieve the same effect, then I know that `uglies[i] * primes[k] `must be not in the heap before, then method 4 works. Is my guess right? If so, can you proof it?  By the way, I think your 5 solutions here are incredible smart and much better than those in leetcode discusion.

**Comment by kamyu104** [comment]
1. In method 4
Your guess is right.
Using hash set is to check duplicates that uglies[i] * primes[k] has been already  in heap.
If not, just put a new one multiplied by primes[k] on the heap.
Besides, there always exists a number in generated uglies satistifying that uglies[i] * primes[k] is not a duplicate.
For exmaple, the just confirmed ugly number which is currently the largest and never multiplied by other primes.

2. In method 1
Genereating  uglies[i] * primes[k] in ascending rule is to simplify checking  duplicates that has been already in heap. It is faster than method 4.
