### ISSUE TITLE
remove-duplicates-from-sorted-array can be better

### ISSUE THREAD

**Issue by txytju** [kamyu104/LeetCode#135]
[LeetCode/remove-duplicates-from-sorted-array.py](https://github.com/txytju/LeetCode/blob/master/Python/remove-duplicates-from-sorted-array.py) will be better if you add `i += 1` to the if part.

**Comment by kamyu104** [comment]
Thanks for suggestion. But I dont't fully understand what you mean. If I added al`i += 1` to the if part, it will miss some element to compare and get wrong.
