### ISSUE TITLE
link error in README.md line 286

### ISSUE THREAD

**Issue by zhihaoyu** [kamyu104/LeetCode#14]
https://leetcode.com/problems/move-zeroes/

**Comment by yanjiao** [comment]
This is an automatically generated message.

yanjiao@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by kamyu104** [comment]
Thanks for your friendly reminder. I have updated it.

**Comment by zhihaoyu** [comment]
another link error in line 218, https://leetcode.com/problems/bulls-and-cows/
