### ISSUE TITLE
bugs in INT_MIN

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode#143]
https://github.com/kamyu104/LeetCode/blob/e5a2dc1ba7b94b4992314dd3bfaf384cd88e6f15/C%2B%2B/third-maximum-number.cpp#L8

if the input is [-2147483648, 1, 2], this solution outputs 2, but the right answer is -2147483648

**Comment by kamyu104** [comment]
Thanks, I'll fix it.
