### ISSUE TITLE
this complexity seems incorrect

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode#153]
https://github.com/kamyu104/LeetCode/blob/58af50ef4f3e502b3f246a123667c9dda7832323/C%2B%2B/implement-rand10-using-rand7.cpp#L35

T = lim(n->inf) [1 * (40 / 49) +  2 * (9 / 49) * (40 / 49)  + ... + n * (9 / 49) ^ (n - 1) * (40 / 49)] = 49 / 40 = 1.225

**Comment by kamyu104** [comment]
No, each time takes 2 rand7(). Thus 2 * 1.225 = 2.45
