### ISSUE TITLE
A Problem on "287	Find the Duplicate Number"

### ISSUE THREAD

**Issue by haoyudong** [kamyu104/LeetCode#16]
Hello, First, I really appreciate you for your simple code and intelligent solutions. And I benefit a lot from your github.
However, I think there is something wrong on the first solution--"cycle list" of 287.
Please consider the situation"[1,0,1]". The right answer is 1. However, this solution has a cycle in 0 and 1.

**Comment by kamyu104** [comment]
Thanks for your friendly reminder!

As the problem described, "Given an array nums containing n + 1 integers where each integer is between 1 and n (inclusive)", so there will be no 0 in the given array. The solution works only if the given array is as described.

**Comment by haoyudong** [comment]
I got it. It is a good approach. Thanks!

**Comment by pangjac** [comment]
eeeeree

via CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.12.43&pv=9.2.1&source=email_footer_2>
