### ISSUE TITLE
why is the worst space O(k ^ 2)

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode#161]
https://github.com/kamyu104/LeetCode/blob/4456697bb19a3b7018f339007957a0f727bde394/C%2B%2B/super-ugly-number.cpp#L71

Every time you can add at most k new numbers into the heap, and you need to do this n times, so I think the worst space is O(n * k)

**Comment by kamyu104** [comment]
Yes, you are right, I'll correct it. Thanks for reminding.
