### ISSUE TITLE
Redundant manipulation in Remove Duplicates from Sorted List II list

### ISSUE THREAD

**Issue by AngLi-Leon** [kamyu104/LeetCode#17]
Is line40 in [LeetCode/Python/remove-duplicates-from-sorted-list-ii.py](https://github.com/kamyu104/LeetCode/blob/master/Python/remove-duplicates-from-sorted-list-ii.py) `pre.next = cur` redundant? Pls help check.

**Comment by AngLi-Leon** [comment]
Since in line31 you have already linked the dummy node to the list and each time when you remove the duplicates, you link the pre to the cur (line38).

**Comment by kamyu104** [comment]
Yes, you are right! Thank you for your advice. I'll update it!
