### ISSUE TITLE
More simpler solution for Longest Palindromic Substring - Python

### ISSUE THREAD

**Issue by anuragkanungo** [kamyu104/LeetCode#33]
class Solution(object):
    
    def linear(self, s):
        if not s:
            return ""

        n = len(s)
        
        longest = s[0:1]
        
        for i in xrange(n-1):
            temp = self.expand(s,i,i)
            
            if len(temp) > len(longest):
                longest = temp

            temp1 = self.expand(s,i,i+1)

            if len(temp1) > len(longest):
                longest = temp1
        
        return longest

    def expand(self, s, begin , end):
        while (begin >= 0) and (end <= len(s) - 1) and (s[begin] == s[end]):
            begin -= 1
            end += 1
            
        return s[begin+1:end]

    def dp(self, s):
        
        if not s:
            return ""
        n = len(s)
        
        dp = [[False for _ in xrange(n)] for _ in xrange(n)]
        
        for i in xrange(n):
            dp[i][i] = True
            
        max_len = 1
        start = 0
        
        for l in xrange(2,n+1):
            for i in xrange(0,n-l+1):
                j = i + l - 1
                
                if (l == 2):
                    if s[i] == s[j]:
                        dp[i][j] = True
                        max_len = 2
                        start = i
                else:
                    if s[i] == s[j] and dp[i+1][j-1]:
                        dp[i][j] = True
                        
                        if l > max_len:
                            max_len = l
                            start = i
                
        
        return s[start:start+max_len]
            
    def longestPalindrome(self, s):
        """
        :type s: str
        :rtype: str
        """
        return self.linear(s)

**Comment by kamyu104** [comment]
Thanks for your simpler solution. I'll add it into the solutions later!
