### ISSUE TITLE
majority-element.py 中的第一种方法貌似错了

### ISSUE THREAD

**Issue by mikolaje** [kamyu104/LeetCode#50]
for i in xrange(1, len(nums)):
            if nums[idx] == nums[i]:
                cnt += 1
            else:
                cnt -= 1
                if cnt == 0:  
                    idx = i
                    cnt = 1

感觉不对呀

**Comment by kamyu104** [comment]
This problem is tricky. Note that the majority element is is the element that appears more than [n/2] times. And try to think about it :)

**Comment by mikolaje** [comment]
oh,it's my misunderstanding. got it~ thanks :)
