### ISSUE TITLE
Solution3 in first-unique-character-in-a-string

### ISSUE THREAD

**Issue by swaroopgrs** [kamyu104/LeetCode#60]
In firstUniqChar3 you used Counter which is returns an unordered collection.  We need an ordered collection to return the first occurring unique character. Am I missing something here?
```
 def firstUniqChar3(self, s):
        """
        :type s: str
        :rtype: int
        """
        cnt = collections.Counter(s)
        if cnt:
            for i in cnt.keys():
                if cnt[i] == 1:
                    return s.index(i)
            return -1
        else:
            return -1
```

**Comment by kamyu104** [comment]
Yes, you are right. I am going remove some incorrect merged solutions. Thank you for your reminding! :)

**Comment by swaroopgrs** [comment]
Thank you for such an awesome repo :)
