### ISSUE TITLE
Space Complexity LFU Cache

### ISSUE THREAD

**Issue by burakcoskun** [kamyu104/LeetCode#67]
How come it can be O(k) space complexity where k is the cache size. In order not to loose frequency of any element, should not we need to store all of them . Isn't the minimum space needed for LFU Cache problem is the number of unique elements? 

We can store top k in the cache but we should store everything in the frequency hash table.

**Comment by kamyu104** [comment]
1. We only need to keep the keys and the frequencies of the top k elements. Others would be deleted. Thus we may at most use O(k) space.
2. If the number of unique elements n is less than k, then the space will be O(n), but usually n is much more than k.
