### ISSUE TITLE
Time & Space complexity for Letter-combinations of a phone number

### ISSUE THREAD

**Issue by anukul-mohil** [kamyu104/LeetCode#69]
https://github.com/kamyu104/LeetCode/blob/953e078d0cb847428bac538517d04fc84477be69/Python/letter-combinations-of-a-phone-number.py#L1

Can you explain a bit how time and space complexity is O(n*4^n) and O(n) respectively, where
"n" is the number of digits(For the iterative version).Especially space complexity seems a bit off as this would roughly mean a two digit string like "23" would only require two memory slots.
# Input:Digit string "23"
# Output: ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"].

**Comment by kamyu104** [comment]
1. The space complexity here means extra space we may use. It doesn't include the space used in the output.
2. The time complexity comes from 3-4 possible choices per digit and n-digit string. So there are at most 4^n combinations  and each combination with length n. Thus O(n * 4^n).
