### ISSUE TITLE
How is O(logn) == O(1) here?

### ISSUE THREAD

**Issue by anukul-mohil** [kamyu104/LeetCode#70]
https://github.com/kamyu104/LeetCode/blob/bf3cdf981729e518a98f92ad8e30cccc26731c18/Python/ugly-number.py#L1
Isn't the time complexity here log<sub>2</sub>(n), where n is the input number.
Max of (log<sub>2</sub>(n), log<sub>3</sub>(n), log<sub>5</sub>(n)) therefore log<sub>2</sub>(n). Moreover you should add the base for the log here since that's the difference b/w night and day here.

Thx for the wonderful solutions btw.

**Comment by kamyu104** [comment]
1. In this problem, n is a 32-bit integer. Thus O(logn) would be in  constant time O(1). 
2. Big O doesn't deal with constant factors, and the difference between Logx(n) and Logy(n) is a constant factor. Thus O(logn) is the same of Max of (log2(n), log3(n), log5(n)) .
