### ISSUE TITLE
Shouldn't the time complexity be O(m * k ), where m is string length, k is word length

### ISSUE THREAD

**Issue by anukul-mohil** [kamyu104/LeetCode#71]
https://github.com/kamyu104/LeetCode/blob/b84ccab1f767bc6381f4dcec0ab2d6f5a609933b/Python/substring-with-concatenation-of-all-words.py#L1

Since checking existence of an item in dictionary [here](https://github.com/kamyu104/LeetCode/blob/master/Python/substring-with-concatenation-of-all-words.py#L31) is O(1) in python. I believe time complexity should be O(m * k). 
Also space complexity seems to be O(len(word_list)). where word_list is the list of strings passed as L to your method.
What do you think?

**Comment by kamyu104** [comment]
1. I added some comments in the source code. 
2. Besides, checking existence of an item is O(1) after hashing the key value which also costs O(k).
3. Key value also costs space, so space is O(n * k).
