### ISSUE TITLE
Can you specify what are n and k here?

### ISSUE THREAD

**Issue by anukul-mohil** [kamyu104/LeetCode#72]
https://github.com/kamyu104/LeetCode/blob/1ad86d344f12384e7cd97d7d1ffb41f1784d403f/Python/combination-sum.py#L1

Can you please specify what n and k are in the time and space complexities here?
Also if possible can you also add add comments like you added [here](https://github.com/kamyu104/LeetCode/blob/master/Python/substring-with-concatenation-of-all-words.py#L32), so as to make it more clear how we got there. Seems like finding time complexity for this problem is not very straight forward.

Thanks for maintaining this awesome repo.

**Comment by kamyu104** [comment]
1. k is the max length of each combination as problem describes.
2. For a combination, we may have at most n choices for each number, so there is at most n^k combinations with k-length. Thus, it's O(k *n^k).
3. Currently,  I only added detailed comments for harder problems as I think. Most problems are too trivial to add, I prefer to let learners to figure out it by self.

**Comment by anukul-mohil** [comment]
For your statement: 

> For a combination, we may have at most n choices for each number, so there are at most n^k combinations with k-length. Thus, it's O(k *n^k).

Since every number can have max. n choices and there are max k numbers, we would get
n * n * n * ....k times which would give n^k.
But why did we multiply this by k then to make it k * n^k?
I think it should be p * n ^k where p is the total combinations we produced, k is the max length of each combination and n is the total number of candidates.

**Comment by kamyu104** [comment]
1. n^k is the max total combinations we could produce. Each combination is with at most length k.
2.  Time complexity would be "the max length of one combination (k) * the max count of total combinations (n^k)". It's O(k * n^k)  .
