### ISSUE TITLE
Hi , 

### ISSUE THREAD

**Issue by emmawu0310** [kamyu104/LeetCode#74]
Hi, I came across your code while searching for a better solution for a question from Leetcode. https://github.com/kamyu104/LeetCode/blob/master/Python/maximum-binary-tree.py

I was first impressed that you can achieve this with time complexity of O(n), but second thought is that every time you pops the element, you have to do a O(n) comparison for all the elements in the stack. Doesn't that make the total complexity of O(n2)?

**Comment by pawankumbhare4213** [comment]
Na

**Comment by kamyu104** [comment]
All elements will be pushed and popped at most once, thus time O(n).
